### ISSUE TITLE
Client isn't safe for concurrent requests

### ISSUE THREAD

**Issue by antoineco** [kraftcloud/go-sdk#7]
The following pattern isn't safe for concurrent requests:

https://github.com/kraftcloud/go-sdk/blob/7507ff066df3b4d71bdb94b21fb6d74cddf60931/instance/client.go#L18-L21

https://github.com/kraftcloud/go-sdk/blob/7507ff066df3b4d71bdb94b21fb6d74cddf60931/instance/instance_create.go#L77-L81

**Comment by antoineco** [comment]
Although the problem should be obvious, I am including a test case which demonstrates the issue.

### Test code

Given two instances which I pre-created on my KraftCloud account, the following code requests their status concurrently and asserts that the response contains the expected UUID.

Due to the non thread-safe code, one call to `Status()` eventually returns the wrong UUID because `cli.request` gets overwritten by another concurrent `Status()` function call.

```golang
package kraftcloud_test

import (
	"context"
	"sync"
	"testing"

	"sdk.kraft.cloud"
	"sdk.kraft.cloud/instance"
)

const token = "<redacted>"

func TestClientRace(t *testing.T) {
	const (
		instance1 = "3ce45bbf-5921-4590-ba1f-611da83871a0"
		instance2 = "61b1a043-f9b5-4751-8b60-5c2f18ebd68c"
	)
	const requests = 50

	cli := instance.NewInstancesClient(
		kraftcloud.WithToken(token),
	)

	var wg sync.WaitGroup

	for _, uuid := range []string{instance1, instance2} {
		wg.Add(1)
		go func(uuid string) {
			defer wg.Done()
			for i := 0; i < requests; i++ {
				ins, err := cli.Status(context.Background(), uuid)
				if err != nil {
					t.Error("Status:", err)
					continue
				}
				if ins.UUID != uuid {
					t.Errorf("Expected uuid %s, got %s:", uuid, ins.UUID)
				}
			}
		}(uuid)
	}

	wg.Wait()
}
```

### Execution

```console
$ go test -count=1 -race .
==================
WARNING: DATA RACE
Read at 0x00c000026298 by goroutine 8:
  sdk.kraft.cloud/instance.(*instancesClient).Status()
      /go-sdk/instance/instance_status.go:27 +0x1bd
  sdk%2ekraft%2ecloud_test.TestClientRace.func1()
      /go-sdk/main_test.go:32 +0x109
  sdk%2ekraft%2ecloud_test.TestClientRace.func3()
      /go-sdk/main_test.go:41 +0x4f

Previous write at 0x00c000026298 by goroutine 9:
  sdk.kraft.cloud/instance.(*instancesClient).Status()
      /go-sdk/instance/instance_status.go:28 +0x290
  sdk%2ekraft%2ecloud_test.TestClientRace.func1()
      /go-sdk/main_test.go:32 +0x109
  sdk%2ekraft%2ecloud_test.TestClientRace.func3()
      /go-sdk/main_test.go:41 +0x4f

Goroutine 8 (running) created at:
  sdk%2ekraft%2ecloud_test.TestClientRace()
      /go-sdk/main_test.go:29 +0x194
  testing.tRunner()
      /go1.21.2/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /go1.21.2/src/testing/testing.go:1648 +0x44

Goroutine 9 (running) created at:
  sdk%2ekraft%2ecloud_test.TestClientRace()
      /go-sdk/main_test.go:29 +0x194
  testing.tRunner()
      /go1.21.2/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /go1.21.2/src/testing/testing.go:1648 +0x44
==================

(+ 4 more occurrences)

--- FAIL: TestClientRace (6.73s)
    testing.go:1465: race detected during execution of test
```

That's 5 racy read-write accesses with just 2x50 requests.

**Comment by antoineco** [comment]
Additionally, I was able to cause a `nil` pointer dereference at the following line with the race detector **disabled**:

https://github.com/kraftcloud/go-sdk/blob/7507ff066df3b4d71bdb94b21fb6d74cddf60931/service_request.go#L65-L66

`request` was overwritten as `nil`, so the test panicked:

```console
$ go test -count=1 .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x68c73c]

goroutine 21 [running]:
sdk%2ekraft%2ecloud.(*ServiceRequest).Metrolink(0xc000105d70?, {0xc000553290, 0x2f})
        /go-sdk/service_request.go:66 +0x1c
sdk%2ekraft%2ecloud.(*ServiceRequest).DoRequest(0xc000105eb8?, {0x794980, 0x994c00}, {0x7102ef, 0x3}, {0xc000553290?, 0x0?}, {0x0, 0x0}, {0x6c84a0, ...})
        /go-sdk/service_request.go:77 +0x77
sdk.kraft.cloud/instance.(*instancesClient).Status(0xc000098250, {0x794980, 0x994c00}, {0x71d15b?, 0x0?})
        /go-sdk/instance/instance_status.go:34 +0x1f2
sdk%2ekraft%2ecloud_test.TestClientRace.func1({0x71d15b, 0x24})
        /go-sdk/main_test.go:33 +0xdb
created by sdk%2ekraft%2ecloud_test.TestClientRace in goroutine 19
        /go-sdk/main_test.go:30 +0x113
FAIL    sdk.kraft.cloud 56.966s
FAIL
```

**Comment by nderjung** [comment]
Thanks for fixing this! 🔥 💯
